### ISSUE TITLE
the epdfinfo server quit

### ISSUE THREAD

**Issue by zhengjiezxxy** [politza/pdf-tools#108]
Suddenly emit this error after some reboot of emacs

logs of /tmp/epdfinfo

epdfinfo: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.

libpoppler version 0.33 latest

**Comment by gbby** [comment]
I just installed pdf-tools from melpa (emacs 24.3 with libpoppler .34 that I built from scratch). M-x pdf-tools-install seems to have worked, but it immediately prompts "the epdfinfo server quit, restart it?" endlessly. Any thoughts? Would love to get pdf-tools up and running on this machine!!

**Comment by politza** [comment]
Sounds like a linker problem.

**Comment by gbby** [comment]
I just deleted and rebuilt from melpa. When it builds the server, this is the one caution that it throws:

epdfinfo-epdfinfo.o: In function `mktempfile':
/home/gbby/.emacs.d/elpa/pdf-tools-20150716.643/build/server/epdfinfo.c:272: warning: the use of `tempnam' is dangerous, better use `mkstemp'

Otherwise, it suggests that the server was built successfully...

**Comment by politza** [comment]
Try to run the server in a terminal...

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: gbby <notifications@github.com> </div><div>Datum:04.08.2015  23:27  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de> </div><div>Betreff: Re: [pdf-tools] the epdfinfo server quit (#108) </div><div>
</div>I just deleted and rebuilt from melpa. When it builds the server, this is the one caution that it throws:

epdfinfo-epdfinfo.o: In function mktempfile':
/home/gbby/.emacs.d/elpa/pdf-tools-20150716.643/build/server/epdfinfo.c:272: warning: the use oftempnam' is dangerous, better use `mkstemp'

Otherwise, it suggests that the server was built successfully...

**Comment by gbby** [comment]
No luck, and I've tried with different versions of poppler, but to no avail. Had it working fine with poppler .24, but could only do text annotations (no highlights), which is why I upgraded poppler in the first place. Oh well... I'll probably wait until I upgrade my OS to try to get it running again.
