### ISSUE TITLE
Implement push/pop mark feature

### ISSUE THREAD

**Issue by rdiaz02** [politza/pdf-tools#126]
As far as I can see, the usual `C-SPC` and `C-u C-SPC` for `set-mark-command` do not work in pdf-view-mode (I can set mark, or seem to set it, but can not jump back to it). I guess I can do something very similar with `pdf-view-position-to-register` and then `pdf-view-jump-to-register` but this requires extra steps (naming the register) and is not muscle memory. Am I misunderstanding how I can jump to previous positions in the PDF (page I guess is fine, no need for exact line)?

**Comment by politza** [comment]
The mark-commands push/pop a buffer position on/from the local variable `mark-ring`, which is not sufficient for restoring a PDF page (because there is no function mapping byte-offsets to document pages).

In other words this would have to be implemented seperately, e.g. by using the register functions.

**Comment by rdiaz02** [comment]
OK, thanks, understood. i'll keep using registers (and B).

**Comment by rien333** [comment]
```
(define-key pdf-view-mode-map (kbd "C-SPC") 
  (lambda () (interactive) (message "Position saved") (pdf-view-position-to-register ?x)))
(define-key pdf-view-mode-map (kbd "C-U C-SPC") 
  (lambda () (interactive) (pdf-view-jump-to-register ?x)))
```

Although it has some obvious flaws (no history of marks), this actually comes fairly close to how I would use mark's in pdfs anyway. You'll to do the keypresses manually, of course.
