### ISSUE TITLE
Feature suggestion: Optionally open links in indirect buffer

### ISSUE THREAD

**Issue by andersjohansson** [politza/pdf-tools#132]
When reading scientific articles, citations in modern pdfs generally link to the references section. It would be great if these kinds of links could be opened in an indirect buffer (making it easy to switch between references and main text). Would this be possible to do?

I guess it could be done by adding a prefix argument to `pdf-links-action-perform` and make (or select the window if one already exists?) a cloned indirect buffer if prefix-argument is non-nil at: https://github.com/politza/pdf-tools/blob/master/lisp/pdf-links.el#L198

Would this present any problems? Are there any problems with indirect buffers in pdf-view? Would it work both with mouse and keyboard selections of links?

I could code some implementation if it could work.

**Comment by politza** [comment]
Anders Johansson <notifications@github.com> writes:

> When reading scientific articles, citations in modern pdfs generally
> link to the references section. It would be great if these kinds of
> links could be opened in an indirect buffer (making it easy to switch
> between references and main text). Would this be possible to do?

I'm afraid not, since indirect buffers have no buffer-file-name set,
which is a problem.

What you can do is use the history (B and N) and/or registers.
I.e. navigate to the literature section and press ml, which sets the
register l as a bookmark to this page.  Now hitting 'l will get you to
that page, while '' will bring back, at which point it'll toggle between
these two positions.

**Comment by andersjohansson** [comment]
Ok, I guess that of course history and registers work equally well for this case so no real problem here. I don't know if indirect pdf buffers would be useful for something else, but if they won't work well that's of course out of the question. Will close this for now.
