### ISSUE TITLE
Arrow tooltip does not display on Mac 

### ISSUE THREAD

**Issue by ksjogo** [politza/pdf-tools#145]
The mac ns backend of the sync tooltip results in an empty yellow box to be displayed a bit above the beginning of the corresponding line.
The propertized text from `pdf-util-tooltip-arrow` is propertized again, thus resulting in no arrow being displayed. One could possibly return text directly for use with the ns tooltip backend.
Color handling seems to be not supported at the moment at all. But that needs to be changed upstream.

**Comment by politza** [comment]
Johannes Goslar <notifications@github.com> writes:

> The mac ns backend of the sync tooltip results in an empty yellow box to be displayed a bit above the beginning of the corresponding line.

The tooltip may be slightly off due to limitations in Emacs..

> [...] One could possibly return text directly for use with the ns
> tooltip backend. [...]

--- /home/politza/.emacs.d/elpa/pdf-tools-0.70/pdf-util.el
+++ #<buffer pdf-util.el>
@@ -704,7 +704,7 @@
         (cl-incf dx (/ (- xw (car (pdf-view-image-size t))) 2))))
     (pdf-util-tooltip-in-window
      (propertize
-      " " 'display (propertize
+      "\u2192" 'display (propertize
 		    "\u2192" ;;right arrow
 		    'display '(height 2)
 		    'face `(:foreground

Like so ?

**Comment by politza** [comment]
Please open the `...` above.

**Comment by politza** [comment]
I'd need a patch for this, since I don't own a Mac.
