### ISSUE TITLE
Long delays rendering 10M pdf

### ISSUE THREAD

**Issue by bremner** [politza/pdf-tools#176]
I'm not sure if anything can be done, but perhaps this helps as a publicly available test case.

When viewing 

http://jeffe.cs.illinois.edu/teaching/algorithms/all-algorithms.pdf

there are pauses as long as 3 minutes on this reasonably fast machine (3Gz i7 950).

Interestingly mupdf also pauses for a few seconds in some of the same places  and evince for something less than a minute (i.e. paging from page 16 to 17).

**Comment by politza** [comment]
Yes, mupdf does render certain pages dramatically faster than poppler.  pdf-tools and evince should be rougly the same, because both use the same backend. Are you sure you compared equal sized images ?

**Comment by Titan-C** [comment]
I experience long delays even in small files. Take for example this work http://e-collection.ethbib.ethz.ch/eserv/eth:31103/eth-31103-02.pdf#search=%22(author:Gull)%22 it is very slow for all page.
I run arch linux, poppler 0.40, imagemagic 6.9.3.0
If I open the file with Okular it has no delay at all in any page.

**Comment by ardpp** [comment]
@Titan-C I also run arch linux, poppler 0.40, imagemagic 6.9.3.0 (and emacs 25.1.50) and the pdf file you link to opens immediately.

**Comment by Titan-C** [comment]
@ardpp I installed emacs 25.1.50 but I keep having huge delays while opening the pdf. Is there a way to track down what is taking so long? Emacs takes 100%cpu, and rendering freezes.

**Comment by bremner** [comment]
I tested again rendering a single page, and indeed I don't see a huge difference between evince and pdf-tools. So perhaps this issue can be closed.

If you want a kind of 1 page torture test, you can try 

[test.pdf](https://github.com/politza/pdf-tools/files/129214/test.pdf)

Although I guess the license is cc-by-nc, so not so useful for distribution.

**Comment by ardpp** [comment]
@Titan-C I tried the file you linked to initially once again and can confirm what you are describing. First the file loads immediately but then if you scrol from page to page from some point on it gets extremely slow (in my case it was from p. vi to p. vii). Also cpu load is close to 100%

It seems however that there is something special in the file that causes the delay: p. 27 for instance is the same as the test.pdf that @bremner linked to. 

I tried books with 42MB and there I cannot observe such delays.

**Comment by Titan-C** [comment]
Reviewing over this weekend I found out most of my slow down in rendering the pdf was because relative line numbering was activated on the pdf buffer. Now deactivated most of pdfs run fine, and my previous complains were noise.

Now regarding large files. The examples from @bremner are a stress test indseed, but rendering is faster in Okular than with pdf-tools. the switch from pages vi to vii has no delay at all in Okular but it does suffer in pdf-tools. And p.27 or the test.pdf does render faster in Okular.
I tested with larger files, book scans into pdfs(211.7MB). The delay happens after scrolling some pages, but it short and tolerable. Okular presents no noticeable delay
