### ISSUE TITLE
pdf-tools pretty much unusable with linum-mode enabled

### ISSUE THREAD

**Issue by jockej** [politza/pdf-tools#189]
This isn't so much a problem with pdf-tools as with linum, but I thought I might let you know.

If one has (global-linum-mode 1) in one's .emacs, opening a pdf document with pdf-tools pretty much hangs emacs. It's moving a glacial speed (it takes several minutes to open a document even on an i7, let's not talk about my atom powered notebook).

The solution which was provided to me by the helpful folks at #emacs is to put
`(add-hook 'pdf-view-mode-hook (lambda() (linum-mode -1)))` in your .emacs.

So maybe that's worth mentioning in the readme, least somebody thinks there is something wrong with pdf-tools (which I did).

**Comment by kirk86** [comment]
@jockej I tied your suggestion but for me unfortunately it didn't work out even when totally disabling `global-linum-mode`.

I am trying to view a 9.1M pdf file but it is really taking for ages.

This is what I have in my `~/.emacs.d/init.el` for the pdf-tools setup.

`(pdf-tools-install)`
`(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)`

`(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
          #'TeX-revert-document-buffer)`

Since I am new with the world of emacs and maybe I've srewed something up in the process. But when I check with a smaller one page pdf file it works fine but in the case of the bigger 9.1M continuous pdf file it simply hangs even in the first page, and unfortunately I am unable to scroll down to consecutive pages.
