### ISSUE TITLE
wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by kirk86** [politza/pdf-tools#223]
Hello everyone, I've been having an issue lately trying to open some pdf in pdf-view mode.
Every time that I open the pdf I can only see this 
<img width="630" alt="screen shot 2016-08-03 at 1 05 27 pm" src="https://cloud.githubusercontent.com/assets/2902390/17364963/388c911a-597b-11e6-9c77-22cd8568bbb0.png">

And every time that I press the navigation arrows in my keyboard inside that buffer I get the following messages.

`Wrong type argument: number-or-marker-p, "Trace/BPT trap: 5`
`Invalid image specification: nil`

Instead if I change to doc-view `M-x doc-view-mode` then I get the normal pdf output like this

<img width="588" alt="screen shot 2016-08-03 at 1 12 29 pm" src="https://cloud.githubusercontent.com/assets/2902390/17365078/04f82250-597c-11e6-9370-8626151a393d.png">

Here is the output from inside the pdf-view buffer if I execute the debugger `C-x C-e`

`Debugger entered--Lisp error: (void-variable %%EOF)`
  `eval(%%EOF nil)`
  `eval-last-sexp-1(nil)`
  `eval-last-sexp(nil)`
  `#<subr call-interactively>(eval-last-sexp nil nil)`
  `ad-Advice-call-interactively(#<subr call-interactively> eval-last-sexp nil nil)`
  `apply(ad-Advice-call-interactively #<subr call-interactively> (eval-last-sexp nil nil))`
  `call-interactively(eval-last-sexp nil nil)`
  `command-execute(eval-last-sexp)`

How can I resolve this issue? Anyone with similar experience?

Thanks in advance.

**Comment by politza** [comment]
Can you post the PDF file somewhere ?

**Comment by kirk86** [comment]
@politza I've uploaded the pdf here [sample file](http://www.filedropper.com/sample), thanks

**Comment by politza** [comment]
Does this problem arise with only this file or any ?

What is the result of `(pdf-info-number-of-pages "sample.pdf")` ?

**Comment by politza** [comment]
... and what of `(pdf-info-renderpage 1 100 "sample.pdf")` ?

**Comment by kirk86** [comment]
@politza I don't have `(pdf-info-number-of-pages)` nor `(pdf-info-renderpage 1 00)` available as options when I use `M-x` should I put those in the configuration file `.emacs.d`?

Yes this is happening with every pdf.

Here is a more descriptive error message:

`pdf-info-process-assert-running: Wrong type argument: number-or-marker-p, "Trace/BPT trap:` `5"Error during redisplay: (eval (number-to-string (pdf-view-current-page))) signaled (wrong-type-argument numberp nil)`
`Error during redisplay: (eval (number-to-string (pdf-cache-number-of-pages))) signaled (wrong-type-argument number-or-marker-p "Trace/BPT trap: 5")`

**Comment by politza** [comment]
It seems that your build of the epdfinfo program is not setup properly.  Since you are on a mac, I can't really help you with this.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: kirk86 <notifications@github.com> </div><div>Datum:04.08.2016  4:08  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Mention <mention@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] wrong type argument: number-or-marker-p, nil
  (#223) </div><div>
</div>@politza I don't have (pdf-info-number-of-pages) nor (pdf-info-renderpage 1 00) available as options when I use M-x should I put those in the configuration file .emacs.d?

Yes this is happening with every pdf.

Here is a more descriptive error message:

pdf-info-process-assert-running: Wrong type argument: number-or-marker-p, "Trace/BPT trap: 5"Error during redisplay: (eval (number-to-string (pdf-view-current-page))) signaled (wrong-type-argument numberp nil)
Error during redisplay: (eval (number-to-string (pdf-cache-number-of-pages))) signaled (wrong-type-argument number-or-marker-p "Trace/BPT trap: 5")

**Comment by kirk86** [comment]
@politza thanks. What's the proper way to uninstall pdf-tools. I'm gonna try to uninstall and reinstall and see if things change.

I don't have `epdfinfo` in my system but I have `pdfinfo` installed via brew
and I jus run `pdfinfo sample.pdf` and here's the output:

`Title:`
`Subject:`
`Keywords:`
`Author:`
`Creator:        LaTeX with hyper ref package`
`Producer:       pdfTeX-1.40.16`
`CreationDate:   Thu Aug  4 00:20:32 2016 IST`
`ModDate:        Thu Aug  4 00:20:32 2016 IST`
`Tagged:         no`
`UserProperties: no`
`Suspects:       no`
`Form:           none`
`JavaScript:     no`
`Pages:          3`
`Encrypted:      no`
`Page size:      612 x 792 pts (letter)`
`Page rot:       0`
`File size:      45880 bytes`
`Optimized:      no`
`PDF version:    1.5`

**Comment by kirk86** [comment]
Finally solve the problem.
Uninstalled pdf-tools
Install via melba
open emacs, got error message couldn't fine epdfinfo
closed emacs and reopened and every thing worked fine.
