### ISSUE TITLE
Makefile.am suggested modification

### ISSUE THREAD

**Issue by bugaev** [politza/pdf-tools#237]
Hello,

I have successfully compiled the package manually on NixOS.
I had to modify "server/Makefile.am" in order to be able "./configure && make" successfully.
I modified a line on the right side of "=" in Makefile.am as follows:

> libsynctex_a_CFLAGS = -w $(zlib_CFLAGS)

i.e., I added "$(zlib_CFLAGS).
I believe this modification should be done regardless of the system.

Thank you for an awesome package!

**Comment by politza** [comment]
Can you please post the error message if you leave that out.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Viatcheslav Bugaev <notifications@github.com> </div><div>Datum:13.11.2016  8:09  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Betreff: [politza/pdf-tools] Makefile.am suggested modification (#237) </div><div>
</div>Hello,

I have successfully compiled the package manually on NixOS.
I had to modify "server/Makefile.am" in order to be able "./configure && make" successfully.
I modified a line on the right side of "=" in Makefile.am as follows:

libsynctex_a_CFLAGS = -w $(zlib_CFLAGS)

i.e., I added "$(zlib_CFLAGS).
I believe this modification should be done regardless of the system.

Thank you for an awesome package!

**Comment by politza** [comment]
Never mind, it's clear to me why that happens and I just changed it.
