### ISSUE TITLE
DjVu format support

### ISSUE THREAD

**Issue by caadar** [politza/pdf-tools#244]
Please consider to add the DjVu format support. (Doc view mode approch seems unusable for it.)

**Comment by NLisa** [comment]
I would also like to request this feature.

I would love to try and contribute towards this, but have absolutely no idea where to even start...

Maybe a project could be setup to look at this?

**Comment by politza** [comment]
Nyameko Lisa writes:

> I would also like to request this feature.

OK.

> I would love to try and contribute towards this, 

That's good.

> but have absolutely no idea where to even start...

That's bad.

> Maybe a project could be setup to look at this?

That should be fairly easy depending on your Elisp kung-fu.

I have some ideas if you want to go for it.

-ap

**Comment by NLisa** [comment]
> That should be fairly easy depending on your Elisp kung-fu.
Moderate, but I am prepared to put in the time and learn.
>I have some ideas if you want to go for it.
Yes. What did you have in mind?

**Comment by politza** [comment]
OK, here is a way of doing it:

1. Write a function converting X -> PDF.

   You can stay with X=djvu for the time being.  Note, that you don't
   have to implement the actual conversion process -- just use doc-view.

2. Make pdf-view use the generated file.

   Actually I wanted to get this file-handling out of pdf-view, but for
   the moment, I think, the easiest way is to complement the first ~10
   lines of pdf-view-mode.  This code check for a remote or compressed
   file and creates a local/uncompressed copy on which the rest of the
   mode operates.  This temporary filename is saved in
   pdf-view--buffer-file-name.

   Here you want to add a check for a supported file-type and then
   instead of simply copying the file, convert it with your function you
   wrote in step 1.

3. Handle saving the buffer

   Since you probably can't unconvert the file, you need to somehow
   handle the situation, where a user creates some annotations and then
   wants to save the file.

4. Fix all other unanticipated side-effects of the buffer not actually
   being a PDF document.


If some of this does not make sens to you and/or you have a better idea
or questions, just post them.

**Comment by akater** [comment]
> X -> PDF

Some conversion experiments follow. Note: My DocView cache directory is tmpfs mounted. Most of the time with these conversions, my fan spins like mad viewing the result in PDFView (pdf-tools), as if I was watching HD video with a particularly unrestrained player. DocView provides a much better experience with djvus. However, it sorely lacks midnight mode and outline features of PDFView.

We start with some 2.28 Mb djvu file.

`ddjvu -format=pdf -quality=100 -verbose first-input.djvu first-ddjvu.pdf`

Took ≈30 seconds. 24.2 Mb pdf produced. 

`ddjvu -format=pdf -mode=black -quality=100 -verbose first-input.djvu first-ddjvu-black.pdf`

Same ≈30 seconds. 22.4 Mb pdf produced.

`djvups -verbose first-input.djvu | ps2pdf - first-djvups.pdf`
[…]
`GPL Ghostscript 9.21: Unrecoverable error, exit code 1`

4 pages out of ≈400 produced.

`djvups -verbose -gray first-input.djvu | ps2pdf - first-djvups-gray.pdf`

Took about 10 minutes until
`GPL Ghostscript 9.21: Unrecoverable error, exit code 1`
with 3 pages produced.

Another one. djvu file of 926 Kb. 164 pages.
`djvups -verbose second-input.djvu | ps2pdf - second-djvups.pdf`

2 to 3 minutes. 44 Mb pdf. I can barely turn its pages in pdf-tools. Original loads in 2 seconds or so in DocView. Its tiff cache is 21 Mb in total.

`ddjvu -verbose -format=pdf -quality=100 second-input.djvu second-ddjvu.pdf`

6 seconds. 5.45 Mb.

`ddjvu -verbose -format=pdf -mode=black -quality=80 input.djvu second-ddjvu-80.pdf`
`-quality=50` produces file of exactly the same size (a different file, nevertheless).

Same 6 seconds. 4.85 Mb. Somewhat readable but still, freezes at times. I also have 114 Mb 730 pages pdf around, browsing it feels as comfortable as this one, but 730-pages one is typeset.

Looks like djvu better not be converted to PDF. That path is strong with the wrong side of the Force.

**Comment by dalanicolai** [comment]
djvu.el provides quite powerful djvu editing features. I have [extended it a little](https://github.com/dalanicolai/djvu2.el) to show annotations, provide smooth scroll and navigate using imenu a la pdf-tools,. Night-mode should be quite straightforward to implement also (just another imagemagick conversion)
