### ISSUE TITLE
Slow Updates

### ISSUE THREAD

**Issue by DeusProx** [politza/pdf-tools#247]
PDF-Tools seems to update way to slow. After Compiling it takes 2 up to 5 seconds to render the pdf file with actived auto-revert-mode. When using evince it's instantly there.

Is that the normal speed?

**Comment by politza** [comment]
That depends on auto-revert-interval.  But I don't recommend using
auto-revert-mode for this, since it may revert a half-written file
leading to errors.

Use the following instead (needs auctex installed), which will revert
the PDF after every successful compilation.

(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
