### ISSUE TITLE
Server build doesn't work when installed (assimilated) with Borg

### ISSUE THREAD

**Issue by thblt** [politza/pdf-tools#287]
When Pdf-Tools is installed with [Borg](https://github.com/emacscollective/borg), `pdf-tools-install` asks whether it should build the server, then fails with:

```
Need to build the server, do it now ? (y or n) y
Should I try to install dependencies with apt-get ? (y or n) n
pdf-tools--melpa-build-server: No such directory: /home/thblt/.emacs.d/lib/pdf-tools/lisp/build
```

(On a side note, I haven't forgotten about [the NixOS support PR I promised](https://github.com/politza/pdf-tools/issues/279), just haven't found the time. Sorry)

**Comment by thblt** [comment]
After a bit more digging: the problem is that `pdf-tools-install` assumes that the package has been built using the Melpa recipe, which renames `server` to `build`.  The best solution  is then, IMHO, *not* to do this renaming on the recipe.  

Another solution would be for PDF Tools to distinguish if it has been installed through Melpa, or Borg, or something else:

 - If `borg-drone-directory` exists as a variable, and PDF Tools is installed inside this directory, then it can  be assumed installation was performed on Borg.
 -  If `package-directory` exists as a variable, and PDF Tools is installed inside this directory, then it can  be assumed installation was performed through Melpa.
 - an even more brutal (but more general) approach would be to just check which of `./build` or `./server` exists.

If  you tell me which solution you prefer, I can create a PR (faster than the NixOS one, I promise :)

Thanks!

**Comment by politza** [comment]
To be honest, I don't like the current situation where the build is a part of the package installation. 

Anyway, there are two ways to install and build this package: Either by using melpa, or by downloading the repo, compiling the binary, building and installing the package. I assume that borg does a git checkout ? And then what ? How does it know where the Lisp files are,  which also are in different directories (melpa vs. git) ?

Anyway, if there needs to be a solution,  I would prefer one that is nonspecific to any package manager.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Thibault <notifications@github.com> </div><div>Datum:15.07.2017  17:09  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Server build doesn't work when installed
  (assimilated) with Borg (#287) </div><div>
</div>After a bit more digging: the problem is that pdf-tools-install assumes that the package has been built using the Melpa recipe, which renames server to build. The best solution is then, IMHO, not to do this renaming on the recipe.

Another solution would be for PDF Tools to distinguish if it has been installed through Melpa, or Borg, or something else:

If borg-drone-directory exists as a variable, and PDF Tools is installed inside this directory, then it can be assumed installation was performed on Borg.
If package-directory exists as a variable, and PDF Tools is installed inside this directory, then it can be assumed installation was performed through Melpa.
an even more brutal (but more general) approach would be to just check which of ./build or ./server exists.
If you tell me which solution you prefer, I can create a PR (faster than the NixOS one, I promise :)

Thanks!

**Comment by thblt** [comment]
Actually, Borg provides ways to configure the way it should build a package, so the makefile can be run directly.  `pdf-tools-install` will fail at build time, but this is a matter of documentation only.

The only remaining issue lies in the different directory structures of the git repository (as can be cloned as a submodule) and the Melpa build.  I guess modifying the `(defcustom pdf-info-epdfinfo-error-filename` so that it tries to detect the directory structure (either `*.el` is in `$PKG_ROOT/lisp/`, then we have a git clone, and the server is in `$PKG_ROOT/server`; or there's a `build` subdirectory and we have a Melpa package) should be enough to handle that.

What do you think?

> I assume that borg does a git checkout ? 

Exactly.  

> And then what ? How does it know where the Lisp files are,  which also are in different directories (melpa vs. git) ? 

I have no idea.  For PDF Tools, once the build has been done (manually) and the value of   `pdf-info-epdfinfo-program`  updated to reflect the directory structure of the git clone, it works perfectly.  I just checked my install,  and the correct directory is on the load-path.

> Anyway, if there needs to be a solution,  I would prefer one that is nonspecific to any package manager.

Borg actually manages packages as Git submodules, so there's nothing specific about it.  Any solution that works with Borg will work for anyone working with a clone of the repository.

**Comment by politza** [comment]
Yes, we can add a check for `../server/epdfinfo` to the `pdf-info-epfdinfo-program` variable in-order to faciliate a out of repo installation, which seems to be what you are saying.
