### ISSUE TITLE
error in process sentinel: pdf-sync-forward-correlate: epdfinfo: Destination not found

### ISSUE THREAD

**Issue by antoine-levitt** [politza/pdf-tools#302]
When I do "View" on an auctex-managed latex file, I sometimes get the following error:
```
error in process sentinel: pdf-sync-forward-correlate: epdfinfo: Destination not found
error in process sentinel: epdfinfo: Destination not found
```

This is on Linux Mint 18.2, emacs and pdf-tools are at ~master, but this has been happening to me for a while. It happens sporadically, and I haven't been able to pinpoint the precise conditions. When it happens, sometimes trying again works, sometimes it doesn't.  Sometimes killing the tex buffer and opening again works, sometimes it doesn't. Sometimes viewing the pdf in another viewer fixes the problem. When it gets working I don't have any way of triggering the bug again. I don't have any problems when opening a pdf outside of auctex. (sorry, this is a crappy bug report, which is why I waited so long to post it...) 

Possibly relevant config:
```
(setq TeX-view-program-selection '((output-pdf "pdf-tools")))
(setq TeX-view-program-list '(("pdf-tools" "TeX-pdf-tools-sync-view")))
(TeX-PDF-mode 1)
(TeX-source-correlate-mode)
```

(if that's related, I have another bug when upgrading pdf-tools through ELPA where I get the message `No executable `epdfinfo' found` during the upgrade, but it doesn't seem to cause any other trouble)

**Comment by politza** [comment]
One reason could be that the document in the epdfinfo server is out of sync with the one on disk.  I see that you don't seem to revert the PDF buffer after you compiled it.  You should add this

  (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)

to your configuration.  

Also, reexamining the code, it seems that if the TeX-buffer's contents differs from the one in the file, it could lead to a situation where the line, column of the buffer does not exist in the file.  And this may result in the same error.

What you could do, if the error persists, is enable logging by putting the following in your init-file.

  (setq pdf-info-log t)

This will write every request and its corresponding answer to a buffer `*pdf-info-log*`.  A sync-request looks like this:

  synctex-forward-search:${PDF_FILE}:${TEX_FILE}:${LINE}:${COLUMN}

You could use this information in order to check for inconsistencies.  

The error itself is not very specific.  I means that either synctex could not determine the corresponding location in the PDF file (for some reason), or the returned location contains a page-number, which is not valid according to the servers view on the document.

**Comment by antoine-levitt** [comment]
> You should add this
> (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
> to your configuration.

I do have this, should have mentioned. Also the buffer's content is the same as that in the file.

Thanks for the info, next time the bug happens I'll get more info and come back.

**Comment by antoine-levitt** [comment]
OK, so at least one instance of this problem was because my point was after \end{document}. Could pdf-tools just ignore the synchronization request in this case?

**Comment by politza** [comment]
What is wrong with raising an error.

**Comment by antoine-levitt** [comment]
When I do something like `TeX-command-run-all`, it means "compile, then view, then synchronize the location". If synchronizing the location fails, it should still view the document. 

(Also, I did not interpret "epdfinfo: Destination not found" as meaning that the current location was not found in the pdf, but as the executable "epdfinfo" not being found, but possibly that's just me.)

**Comment by politza** [comment]
I guess you are correct: it should at least display the document.

**Comment by politza** [comment]
23ad2428ddb8126c40b27ace6b0c0de76bb769c8
