### ISSUE TITLE
Pdf has no outline - but it does!

### ISSUE THREAD

**Issue by chriad** [politza/pdf-tools#408]
I try to show the outline of the following document (https://www.cs.cmu.edu/~dst/LispBook/book.pdf) and get the message `pdf has no outline`. However when viewing it in evince/ocular/acroread there clearly is an outline.

Why is this?

**Comment by politza** [comment]
If you take a closer look and start evince from the command line, you'll see multiple error messages about an unsupported index type.  That's because the PDF's index contains exclusively javascript elements.  Neither pdf-tools nor evince handle these properly, i.e. you can't follow them (with a mouse-click).  But while pdf-tools suppresses these kind of elements completely, evince still shows their titles in the outline bar.
