### ISSUE TITLE
Add memory limit for page cache 

### ISSUE THREAD

**Issue by nnicandro** [politza/pdf-tools#467]
In addition to `pdf-cache-image-limit` it would be beneficial to also have something like `pdf-cache-memory-limit` which would limit the amount of memory the cache uses by calling `image-flush` on the image specs of old pages in the cache once the limit is reached. This would allow `pdf-tools` to manage its memory usage a little better and solve issues like #177.

I'm thinking we do the following:

In `pdf-view-create-page`, associate the image data with the image spec that will be shown

```emacs-lisp
(let ((spec (pdf-view-create-image data
              :width (car size)
              :map hotspots
              :pointer 'arrow)))
  (prog1 spec
    (when (get-text-property 0 'spec data)
      (image-flush (get-text-property 0 'spec data)))
    (put-text-property 0 1 'spec spec data)))
```

Then, as a last step in `pdf-cache-put-image` we scan the cache and calculate the total number of bytes used in the internal image cache by using `image-size` called on the value of the `spec` property of `data`. This is of course assuming that the image specs are still in the internal cache.

If the total number of bytes is larger than `pdf-cache-memory-limit`, we call `image-flush` on the `spec`s of old pages and set the `spec` property to nil indicating that in future number of bytes calculations those pages should not contribute to the calculation since there images have already been flushed.

So a nil value of the `spec` property means that the page data is not cached in the internal image cache, while a non-nil value means that most likely it is.

Thoughts?

**Comment by politza** [comment]
The problem we face is that Emacs has no function for flushing images containing the data directly, but only file-based ones.  So, attaching the images to the data seems like the way forward.  

But, what are proposing is yet another hack in the endless stream of hacks that is the Emacs world.  Something that I'm really tired of.  Maybe we can come up with a better way, at the very least properly hiding this linking behind some functions.

Some other things to consider are:

* Should the limit be global ?  If not, the cache may still grow indefinitely simply by opening more PDF documents.
*  What contributes to the amount of memory an image requires ?  
   1. The data string in the image.
   2. Possibly the same data copied into the image-library.
   3. The displayed image, e.g. a pixmap (I think) in xorg.
* Would the current solution maybe suffice, if we'd additionally flush images when they are released from the cache ? 
* Under what additional circumstances should images be flushed ?  E.g. when a buffer is un-displayed ?

**Comment by politza** [comment]
I couldn't sleep, so I started working on this.

**Comment by politza** [comment]
I think, another problem is that we don't actually know if an image in some situation is cached by Emacs or not and if that image is going to be needed by PDF Tools in the near future.  This combined could paradoxically lead to the undesirable effect of needlessly loading a bunch of images in order to determine their sizes, in order to save memory.

**Comment by politza** [comment]
See http://lists.gnu.org/archive/html/emacs-devel/2019-01/msg00737.html .

**Comment by dzop** [comment]
> Should the limit, or event the cache, be global ? If not, the cache may still grow indefinitely simply by opening more PDF documents.

It would make more sense to be global. Convert the cache into a global alist that maps PDF file names with their caches? But when flushing images after the limit has been reached how would we choose which images should be flushed? 

Would it make sense to store a timestamp for when the image was cached and then when the limit has been reached, we order all of the images in the cache by the timestamp and flush those that are still in the internal image cache (those images whose timestamps are newer than `image-cache-eviction-delay`).

Adding timestamps would also remove the need to call `image-size` on those images with timestamps older than `image-cache-eviction-delay`. Since we already know that they are not in the internal cache.

> What contributes to the amount of memory an image requires ?

It would be much simpler to just consider the pixel data for right now and I suppose the PNG string.

I am not familiar with any other places where memory would be used by PDFs. I didn't know that the image library copies over the PNG data, so we may have to consider that as well.

> Would the current solution maybe suffice, if we'd additionally flush images when they are released from the cache ?

There is a lot of variability in the width of a PDF and therefore also in the resulting number of pixels used to display a page. I think this has to do with the bounding box of a page and the size returned by `pdf-view-desired-image-size`. So even if we flush images as they are released from the cache, the total memory usage can still be quite large and dependent on the PDF.

> Under what additional circumstances should images be flushed ? E.g. when a buffer is un-displayed ?

I think if we converted the cache to be global and with a timestamp for when the images were cached then we don't have to consider this since the condition for when an image is flushed would be based solely on the timestamp and the memory limit.

**Comment by dzop** [comment]
I did look into modifying the internal Emacs image cache since they already timestamp the images that were added to the cache and it definitely makes more sense to do this kind of thing internally. Your patch to Emacs looks good!
