### ISSUE TITLE
mouse-down seems to activate zoom

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#473]

**Comment by titaniumbones** [comment]
In recent versions of pdf-tools mouse-down-1 activates selection but also, osmetimes, activates zoom in the document. THis interferes with precise text selection and basiclaly makes highlight impossible.

Using recent emacs git, on arch linux/gnome.  

Not sure how to diagnose -- I suppose the problem could be in the underlying image view mode?

**Comment by politza** [comment]
Does it happen with `emacs -Q` after loading `pdf-tools` ?

**Comment by wentasah** [comment]
I have the same problem. It happens with `emacs -Q` when `pdf-view-image-relief` is set to 1.

**Comment by fraricci** [comment]
is there a solution for this?
thanks

**Comment by wentasah** [comment]
In my case, the reason was having `pdf-view-image-relief` set to non-zero value. Setting it back to zero (default) prevented the unwanted zooming.

**Comment by fraricci** [comment]
thanks for your reply!
I have that variable set to 0 but it keeps zooming while I'm selecting. Very annoying.

**Comment by surfcao** [comment]
Same issue here on MacOS. Set `pdf-view-image-relief` to zero does not solve the issue.

**Comment by vedang** [comment]
This repo is no longer maintained. Can you please update your setup to fetch from https://github.com/vedang/pdf-tools and then try again? IF you are using MELPA or NonGNU ELPA for package management, simply uninstall and reinstall the package.

If the problem persists, please open an issue against `vedang/pdf-tools` so that I can track and fix  it. That is the official maintained repo now.

Please close this issue as it helps me keep track of new issues on `politza/pdf-tools`.
