### ISSUE TITLE
Is it possible to modify the background color only?

### ISSUE THREAD

**Issue by ericdanan** [politza/pdf-tools#491]
Hello,

I would like to set the background color to a light grey instead of white, without altering the foreground, but couldn't find a way to do it. Is this possible?

 The closest I could get was to customize the variable `pdf-view-midnight-colors` (using either black or nil for the foreground), but then the foreground is all black (e.g. a blue hyperlink turns black). I also tried defining a minor mode similar to `pdf-view-midnight-minor-mode` except that it sets the background color only, but that made no difference.

**Comment by politza** [comment]
No, that would require a different image-filter. One that replaces one color with another.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Eric Danan <notifications@github.com> </div><div>Datum:26.04.2019  12:05  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: [politza/pdf-tools] Is it possible to modify the background color
  only? (#491) </div><div>
</div>Hello,

I would like to set the background color to a light grey instead of white, without altering the foreground, but couldn't find a way to do it. Is this possible?

The closest I could get was to customize the variable pdf-view-midnight-colors (using either black or nil for the foreground), but then the foreground is all black (e.g. a blue hyperlink turns black). I also tried defining a minor mode similar to pdf-view-midnight-minor-mode except that it sets the background color only, but that made no difference.

**Comment by ericdanan** [comment]
Thanks.
