### ISSUE TITLE
Mark with keyboard

### ISSUE THREAD

**Issue by pank** [politza/pdf-tools#52]
It would be nice if it was possible to select regions with the keyboard.  I guess that corresponds to having a cursor.  For instance, it would be much easier to select a region for highlight with usual navigation keys compared to the mouse.  I don't know if this is feasible, though.

**Comment by politza** [comment]
I think displaying a cursor is taking to far, considering the limitations of the display.  Remember that for every changing pixel a new image has to be generated and loaded.

Also, there is currently no `display-manager', for lack of a better term.  This is no problem with isearch, since it's modal, but already a bit messy in the other two cases where additional things are displayed.

What I could see is something like `rectangle-mode`, with a corner in one corner and the region can be expanded by the equivalents of `forward-char` etc, see `pdf-info-charlayout`.

Though I'm not planning on implementing this anytime soon.

**Comment by WorldsEndless** [comment]
For what it's worth, I've had the same wish as a feature request. I was hoping that doing isearch and then 'M-w' to select forward (as with text-buffer searches) would work. Hopefully someday! In the meanwhile, I can make due with the mouse.

**Comment by marion06** [comment]
This could be made just as it is in Conkeror web browser : I-search to the beginning of the text that needs to be selected, and than use 'C-F' , 'C-B', 'C-N', 'C-P', 'M-F', 'M-B' to navigate from that position, just like those shortcuts do in emacs, but lower-cased.
