### ISSUE TITLE
"Destination not found" with forward and backward search with specific source file

### ISSUE THREAD

**Issue by real-or-random** [politza/pdf-tools#526]
I have a document for which forward and backward search works (with auctex). It's a multi-file doc.

However, neither direction works when a specific source file. When I invoke the auctex view command in this source file, I get `epdfinfo: "Destination not found"`. Equally, when I click on a location in the PDF which corresponds to that source file, I get the same error message.

Here are some (useless?) logs:
```
21:12:07 synctex-backward-search:/redacted/main.pdf:2:0.2033898305084746:0.6039279869067103
21:12:08 ERR
Destination not found
.
21:12:22 synctex-forward-search:/redacted/main.pdf:/redacted/./intro.tex:142:100
21:12:23 ERR
Destination not found
```

Any ideas? How could I debug this further?

**Comment by politza** [comment]
The error means that the synctex library returned no result.  It's either a limitation or a bug.

We could try to update synctex if there's a new version available.

**Comment by real-or-random** [comment]
It works fine with Zathura here, so updating synctex may indeed be a good idea.

**Comment by politza** [comment]
I've updated to the latest synctex version [here](https://github.com/politza/pdf-tools/pull/527).  Please try it and see if fixes this issue.  

In order to do that you should check out that branch.  Enter `make melpa-package` in its root-directory, uninstall pdf-tools in Emacs and restart it and finally install the resulting tar via `package-install-file`.
