### ISSUE TITLE
pdf-tools freezes my laptop

### ISSUE THREAD

**Issue by jcguu95** [politza/pdf-tools#535]
`pdf-tools` freezes my laptop, and I had to force shutdown the computer to escape. `C-g` does not work either. Should I provide further information?

**Comment by oscarfv** [comment]
You barely described the problem. Are you using Emacs 27? If yes, does the problem look like #513 ?

If not, please provide a description of your software (OS name and version, Emacs version, pdf-tools version) and a detailed recipe for reproducing the problem, preferably starting with `emacs -Q`.

**Comment by randomwangran** [comment]
Please be polite @oscarfv.

This man is probably running Emacs on Electronic Numerical Integrator and Computer.  Although his computer might be Turing-complete, he probably had hard time.

So, just be patient. Maybe he will provide the information he has and we can help.

**Comment by politza** [comment]
Maybe the cause is actually of an ecological nature.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: randomwangran <notifications@github.com> </div><div>Datum:06.02.2020  6:40  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] pdf-tools freezes my laptop (#535) </div><div>
</div>Please be polite @oscarfv.

This man is probably running Emacs on Electronic Numerical Integrator and Computer. Although his computer might be Turing-complete, he probably had hard time.

So, just be patient. Maybe he will provide the information he has and we can help.
