### ISSUE TITLE
Changing page with DOWN key

### ISSUE THREAD

**Issue by slk500** [politza/pdf-tools#576]
It's weird and very frustrating bug. I can't go to next page with DOWN key (but it works for UP key to go to prev one). So I press 'n' or 'PageDown' and the screen changes to blank, then if I press DOWN it will take 2 pages forward.   

Emacs 27.0.91 
It works fine on my other computer with Emacs 26.1.

**Comment by phil-s** [comment]
* `<down>` calls `pdf-view-next-line-or-next-page`
* `<up>`  calls `pdf-view-previous-line-or-previous-page`

Usually they only scroll line by line; but if showing that line necessitates changing page, it will do that.  So it depends on what portion of the page is visible in the window.  If the whole page is visible (e.g. when you fit-to-page with `P`) then `<down>`/`<up>` should have the same effect as `<next>`/`<prior>` and `n`/`p`.

It *sounds* like your problem is that one of the pages is being rendered as a blank page, so it's unclear why you're mixing the different kinds of navigation command, or whether doing so actually has any relevance.  If it *is* relevant, you should explain how.

I can't replicate your problem using 27.0.91.

**Comment by aksharvarma** [comment]
I also initially had this exact same problem that showed up only in Emacs 27.1 but wasn't there in Emacs 26. I tracked the problem to using an obsolete version of pdf-tools, the 0.90 version, which is the last tag that shows up on Github. I believe that it was a result of faulty config and/or package management on my part which resulted in the 0.90 version being used instead of building updated versions from melpa. 

The issue was fixed by reinstalling pdf-tools from melpa, the 20200512.1524 version of pdf-tools doesn't have this problem on Emacs 27.1.

Hope this helps in case @slk500 is still having issues and/or if anyone else ends up with the same issue.
