### ISSUE TITLE
Anonymize comments

### ISSUE THREAD

**Issue by kgenin** [politza/pdf-tools#613]
When reviewing journal articles, I often find myself having to anonymize all the annotations. Is there a way to change the annotation labels in bulk to replace my name with 'Anonymous Reviewer'?

**Comment by dalanicolai** [comment]
You can start from this function
```
(defun replace-annot-label (new_label)
  (interactive "sType new label: ")
  (let ((annots (pdf-info-getannots)))
    (dolist (x annots) (when (alist-get 'label x)
                         (pdf-info-editannot (alist-get 'id x) (list (cons 'label new_label)))))))
```
which replaces all annotation labels. If you want to match a certain label value, then you should add a condition in the `when` macro. See [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Comparison.html#Text-Comparison)

**Comment by kgenin** [comment]
Thank you! pdf-tools is great.

**Comment by dalanicolai** [comment]
I fully agree, but I am only a user b.t.w. Anyway, there is also the annot list under shortcut `, a h`. You find more info [here](https://github.com/politza/tablist). Also don't forget to read documentation of modes you are using.

I guess you can close this issue. I can't, because I am only a user and don't have the right permissions.
