### ISSUE TITLE
Searching causes zooming causes...unclear

### ISSUE THREAD

**Issue by jeffalstott-iarpa** [politza/pdf-tools#634]
New install of Doom Emacs, with the "pdf" option to get pdf-tools all set up. Everything seems to be working ok, and then I try searching. The effect is best described visually:

Just about to search
![image](https://user-images.githubusercontent.com/66686762/99706854-ae5a0580-2a69-11eb-9db5-e01e62e2803e.png)
typed "b"
![image](https://user-images.githubusercontent.com/66686762/99706907-c0d43f00-2a69-11eb-8ce1-1dc6670caecd.png)
Oh, it started zooming. I...guess that makes sense? Let's type "a"
![image](https://user-images.githubusercontent.com/66686762/99706966-d184b500-2a69-11eb-95ae-dc4398375b95.png)
Uh, that's a bit much zoom. Let's type "c"
![image](https://user-images.githubusercontent.com/66686762/99707008-e103fe00-2a69-11eb-890e-169089d15ca8.png)
Uuuuh. "k"
![image](https://user-images.githubusercontent.com/66686762/99707090-fe38cc80-2a69-11eb-8edf-631c17039e64.png)

As this is my first time using pdf-tools, I hope that I'm just misunderstanding something about the interface.

**Comment by rm413** [comment]
I'm not having that problem. I'm currently using
```
$ emacs --version
GNU Emacs 27.1
```
```
$ find ~/.emacs.d/elpa -maxdepth 1 -type d -name '*pdf-tools*'
/home/beep1560/.emacs.d/elpa/pdf-tools-20200512.1524
```
In the gif shown below, you can see that searching doesn't cause zooming in my Emacs setup

![2020_11_19__18_50_00](https://user-images.githubusercontent.com/74389646/99739111-014bb100-2a9a-11eb-9f2f-731349b935a3.gif)

If you are searching a workaround, you could try executing `pdf-occur` instead of `isearch-forward`. By default, `pdf-occur` it is mapped to `M-s o`.

![2020_11_19__18_50_20](https://user-images.githubusercontent.com/74389646/99739117-07da2880-2a9a-11eb-889c-524538818a1d.gif)

I've mapped `n` and `p` to execute `next-error-no-select` and `previous-error-no-select` in `pdf-occur` buffers so that I can visit ocurrences easily. If I recall correctly, the default mappings for the functions that accomplishes the similar behavior are `M-g n` (`next-error`) and `M-g p` (`previous-error`).

```
(require 'pdf-occur)

(define-key pdf-occur-buffer-mode-map (kbd "n") 'next-error-no-select)
(define-key pdf-occur-buffer-mode-map (kbd "p") 'previous-error-no-select)
```

Note that the difference between `pdf-occur` and `isearch-forward` is that the former will inspect the entire document while the latter will stop at the first match found and will keep searching if the user wants to visit the next occurrence.

**Comment by jeffalstott-iarpa** [comment]
`pdf-occur` gives the same zooming behavior for me:
![image](https://user-images.githubusercontent.com/66686762/99740109-496bd300-2a9c-11eb-97d6-f0182bbe5f9b.png)
And after hitting return on the first occurrence found:
![image](https://user-images.githubusercontent.com/66686762/99740172-6bfdec00-2a9c-11eb-829c-ea36220a5345.png)

> Note that the difference between `pdf-occur` and `isearch-forward` is that the former will inspect the entire document while the latter will stop at the first match found and will keep searching if the user wants to visit the next occurrence.

I'm not following the difference: It looks like `isearch-foward` highlights all instances of the word and placing your cursor on the first one, so it must be inspecting the entire document as well (or at least the current page).

**Comment by rm413** [comment]
I don't have any idea what is causing your issue. However, some information that might be useful to other people willing to solve this issue is the version of Emacs you are using and the version of `pdf-tools`. I tried inspecting the source code of Doom Emacs  with the hope that there was a configuration that was setting this behavior but didn't find any significant.

In regard to the difference between `isearch-forward` and `pdf-occur`. The reason why I stated that `isearch-forward` searches until an ocurrence is found is the fact that when I pressed `C-s` repeatedly in a PDF file, the message `Searching...{percentage}%` was being shown in the minibuffer and Emacs was freezed during that time. For this reason, I think that `isearch-forward` stops when an ocurrence is found and it highlights all the ocurrences present in the page where the ocurrence is found.

Both `pdf-occur` and `isearch-forward` inspect the entire document but `isearch-forward` will stop when it finds the next ocurrence.

**Comment by jeffalstott-iarpa** [comment]
Thanks!

Emacs: GNU Emacs 27.1
pdf-tools: Doom Emacs is currently [pinned](https://github.com/hlissner/doom-emacs/blob/0aab1118deca5e4a7c19eccdbf133d02fad4b5e6/modules/tools/pdf/packages.el) to [this commit](https://github.com/flatwhatson/pdf-tools/commit/eb6d40663069f2b7e6b52e907eeaa4e37375feb6) branch of `pdf-tools`
