### ISSUE TITLE
Disabling automatic revert for pdf-tools

### ISSUE THREAD

**Issue by mcraveiro** [politza/pdf-tools#670]
Hi pdf-tools developers,

thanks very much for a great mode which I use daily. I have hit a very slight snag and I wonder if you can help me with it. In order to make my workflow a bit more responsive, I now export my org-mode files to latex and then run ```latexmk``` on my compilation buffer, like so:

```
latexmk -shell-escape -bibtex -pdf my_file.tex
```

This works quite well, but the only problem is that the pdf-tools buffer is now automatically refreshing during compilation, so my Emacs is again unresponsive during document generation. I'd like to switch off this behaviour and refresh manually instead, when compilation finishes. I have looked at the ```revert-buffer-function``` [1], but as my elisp is not particularly brilliant I could not figure out the correct incantation. I see its set as follows:

```lisp
(setq-local revert-buffer-function #'pdf-view-revert-buffer)
```
But its not clear to me what I should set it to in order to disable reverting. Any help would be greatly appreciated. I did find questions with the opposite problem [2], but could not spot one addressing my issue - apologies if I missed it.

Cheers

Marco

[1] [GitHub: pdf-view.el](https://github.com/politza/pdf-tools/blob/master/lisp/pdf-view.el)
[2] [GitHub: PDF buffer does not revert after AUCTeX compilation when TeX-recenter-output-buffer has been called during compilation #499](https://github.com/politza/pdf-tools/issues/499)

**Comment by vedang** [comment]
`pdf-tools` doesn't do anything special to revert the buffer, the function `pdf-view-revert-buffer` is registered with Emacs (i.e. whenever Emacs decides to revert the buffer, this function is called). 

In your case, I am not able to reproduce this locally - i.e on my system, compiling using `M-x compile` followed by `latexmk` does not automatically revert the buffer displaying the PDF file. This is the expected behavior so I think that something else in your setup is causing this problem. Please check if you have `auto-revert-mode` enabled in your PDF buffer (it should not be enabled by default, as mentioned in the README of this project).
