### ISSUE TITLE
(invalid-function pdf-view-current-page)

### ISSUE THREAD

**Issue by thblt** [politza/pdf-tools#687]
Probably related to #625, in an Emacs built from today's HEAD (`76e846f92a3c625fe524c81aa996327fba5a9e65`) with HEAD pdf-tools, started with `-q`, opening a PDF quickly raises the following error:

```
Debugger entered--Lisp error: (invalid-function pdf-view-current-page)
  pdf-view-current-page()
  pdf-cache-prefetch-pages-function-default()
  pdf-cache--prefetch-start(#<buffer test.pdf>)
  apply(pdf-cache--prefetch-start #<buffer Maison1.pdf>)
  timer-event-handler([t 0 0 500000 t pdf-cache--prefetch-start (#<buffer test.pdf>) idle 0 nil])
```

Evaling the definition of the macro doesn't help, but reimplementing it as a defun does.

**Comment by vedang** [comment]
This repo is no longer maintained. Can you please update your setup to fetch from https://github.com/vedang/pdf-tools and then try again? IF you are using MELPA or NonGNU ELPA for package management, simply uninstall and reinstall the package.

If the problem persists, please open an issue against `vedang/pdf-tools` so that I can track and fix  it. That is the official maintained repo now.

Please close this issue as it helps me keep track of new issues on `politza/pdf-tools`.
