### ISSUE TITLE
Zero or negative size array

### ISSUE THREAD

**Issue by tmtvl** [politza/pdf-tools#699]
When I try to build the epdfinfo program under OpenSUSE Tumbleweed with gcc 11.2.1, it fails with the following errors:

> epdfinfo.c:1764:26: error: zero or negative size array ‘cmd_features_spec’
> epdfinfo.c:1989:26: error: zero or negative size array ‘cmd_regexp_flags_spec’
> epdfinfo.c:2217:26: error: zero or negative size array ‘cmd_quit_spec’

As you appear to be doing some deep macro magic with them, would it be possible to define these with a definite size?
Alternatively, considering they are empty constants, could they be safely removed?

**Comment by vedang** [comment]
This repo is no longer maintained. Can you please update your setup to fetch from https://github.com/vedang/pdf-tools and then try again? IF you are using MELPA or NonGNU ELPA for package management, simply uninstall and reinstall the package.

Please close this issue as it helps me keep track of new issues on `politza/pdf-tools`, and open an issue against `vedang/pdf-tools` so that I can track and fix  it. That is the official maintained repo now.
