### ISSUE TITLE
error when installing pdf-tools

### ISSUE THREAD

**Issue by vanangamudi** [politza/pdf-tools#709]
After installing pdf-tools packages, when I invoke pdf-tools-install I get the following error message.
Emacs version: GNU Emacs 28.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-06-01
Emacs is installed via snap in ubuntu 20.04

```
For information about GNU Emacs and the GNU system, type C-h C-a. 
Need to (re)build the epdfinfo program, do it now ? (y or n) y 
pdf-tools-install: Wrong type argument: (and (not null) file-directory), nil, build-directory
```

**Comment by tongjie-chen** [comment]
Can you do M-x "toggle-debug-on-error" and run again M-x "pdf-tools-install. Then post the backtrace?

**Comment by pierreay** [comment]
For some reasons, the `pdf-tools-locate-build-directory` function used in the `pdf-tools-build-server` function itself called by the `pdf-tools-install` function is not working anymore, because it doesn't correctly detect the source directory. Hence, the build of the `epdfinfo` program at startup time is not working. Hence, when a rebuild is needed, manually evaluate the following command:

`(pdf-tools-build-server (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0")) nil nil nil (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0/server")))`

Obviously, the installation path of `pdf-tools` has to be adjusted if needed. If I have more free time, I hope I will dig into the problem.

**Comment by liesnikov** [comment]
The fix above almost worked for me: `/server/` sits in `/build` subdirectory, so for anyone trying to make it work:
check your pdf-tools version and run 

```
(pdf-tools-build-server (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-VERSION")) nil nil nil (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-VERSION/build/server")))
```
