### ISSUE TITLE
Issue with poppler 0.32. Error in post-command-hook (pdf-tools--upgrade): (error "The epdfinfo server quit unexpectedly.")

### ISSUE THREAD

**Issue by bennylb** [politza/pdf-tools#77]
Arch Linux has just updated to poppler 0.32.

Compilation has the following output which seems ok:

    Running autoreconf...
    configure.ac:15: installing './ar-lib'
    configure.ac:11: installing './compile'
    configure.ac:6: installing './install-sh'
    configure.ac:6: installing './missing'
    Makefile.am: installing './depcomp'

    Is case-sensitive searching enabled ?     yes
    Is modifying text annotations enabled ?   yes
    Is modifying markup annotations enabled ? yes

    config.status: creating config.h
    config.status: config.h is unchanged
    epdfinfo-epdfinfo.o: In function `mktempfile':
    /mnt/ssd-general/Sync/host_configs/common/scratch/pdf-tools/server/epdfinfo.c:270: warning: the use of `tempnam' is dangerous, better use `mkstemp'

But after running `M-x package-install-file RET /home/ben/build/pdf-tools/pdf-tools-0.60.tar RET` I get the following:

    Error in post-command-hook (pdf-tools--upgrade): (error "The epdfinfo server quit unexpectedly.")
    Loading /home/ben/.emacs.d/elpa/pdf-tools-0.60/pdf-annot.el (source)...
    The epdfinfo server quit, restart it ? (y or n) y
    Error in post-command-hook (pdf-tools--upgrade): (error "The epdfinfo server quit unexpectedly.")
    End of buffer [8 times]

Attempting to view a pdf brings up the raw file in PDFView and the message `error "The epdfinfo server quit unexpected` again.

Any ideas?

**Comment by politza** [comment]
Ben Backhouse <notifications@github.com> writes:

> Arch Linux has just updated to poppler 0.32.
> [...]
> Error in post-command-hook (pdf-tools--upgrade): (error "The epdfinfo server quit unexpectedly.")

This is most likely a problem with your environment.  Try to execute
epdfinfo in shell. It will probably complain about a wrong library
version.

**Comment by bennylb** [comment]
Thanks politza, I jumped the gun a bit. I was just in the middle of closing this as removing the existing package from melpa before installing the newly compiled package from git with `M-x package-install-file RET pdf-tools-0.60.tar` fixed the problem.

**Comment by chrstfer** [comment]
I'm seeing this issue right now, on mac osx sierra. 

With emacs closed, I cloned and built the git version--after a bunch of issues, I ended up totally rebuilding my emacs and python environments, converting from separately installed binaries to the homebrew equivalents. I opened a new emacs, and `package-install-file`'d the pdf-tools-0.90.tar file that resulted from the build. Following that,  I did `pdf-tools-install` which froze my emacs. I've read about issues at this step and that sometimes it works after restarting emacs, so after about 5 minutes I force quit, then restarted emacs and tried `pdf-tools-install` again. This time it worked, as I'd hoped, and trying to open a pdf with emacs opened it in `pdf-view-mode`, but I was immediately greeted with the message "the epfinfo server quit." with a popup. If I click yes, it comes again. If I click no, it goes away.  

Running the `epdfinfo` executable doesn't print anything, and it just sits there until I ^C. No errors, doesn't complain about anything in the environment, quits nicely/doesn't hang. Emacs *should* be using the same environment, but who knows. 

The above is just my experience with this most recent attempt. This past evening I originally just tried to install the stable version from melpa, which didn't work. Then for a while the build wasn't working at all, because cask was seeing conflicting emacs binaries in the path or versus the one on my hot bar.  Now everything seems like it should be working, except for something between epdfinfo and emacs. What could be the problem?

**Comment by chrstfer** [comment]
I'm seeing this issue right now, on mac osx sierra. 

With emacs closed, I cloned and built the git version--after few encountering some issues, I ended up totally rebuilding my emacs and python environments, converting from separately installed binaries to the homebrew equivalents. I fixed some .zshrc/.profile issues that were seemingly confusing which binaries were being used, and  added `--debug` to every cask call in the Makefile. After that, the last (most successful so far) build took two `make`s--the first dies with error code 255, the second completes. I've attached the server build output below. This is repeatable, happens after every clean/distclean.

I then opened a new emacs, and `package-install-file`'d the pdf-tools-0.90.tar file that resulted from the build. Following that,  I did `pdf-tools-install` which froze my emacs. I've read about issues at this step and that sometimes it works after restarting emacs, so after about 5 minutes I force quit, then restarted emacs and tried `pdf-tools-install` again. This time it worked, as I'd hoped, and trying to open a pdf with emacs opened it in `pdf-view-mode`, but I was immediately greeted with the message "the epfinfo server quit." with a popup. If I click yes, it comes again. If I click no, it goes away.  

Running the `epdfinfo` executable doesn't print anything, and it just sits there until I ^C. No errors, doesn't complain about anything in the environment, quits nicely/doesn't hang. Emacs *should* be using the same environment, but who knows. 

The above is just my experience with this most recent attempt. This past evening I originally just tried to install the stable version from melpa, which didn't work. Then for a while the build wasn't working at all, because cask was seeing conflicting emacs binaries in the path or versus the one on my hot bar.  Now everything seems like it should be working, except for something between epdfinfo and emacs. What could be the problem?

#### Server Build Output:
```
`--> export path=($HOME/.cask/bin $path)     
.-(~/devel/repos/pdf-tools)--------------------------(chrstfer@ChristophersMBP)-
`--> make                               
Using Emacs 25.3 
cask install --debug
make: *** [.cask/25.3] Error 255
.-(~/devel/repos/pdf-tools)--------------------------(chrstfer@ChristophersMBP)-
`--> make
Using Emacs 25.3 
cd server && ./configure -q

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C server
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.    -w  -g -O2 -MT libsynctex_a-synctex_parser.o -MD -MP -MF .deps/libsynctex_a-synctex_parser.Tpo -c -o libsynctex_a-synctex_parser.o `test -f 'synctex_parser.c' || echo './'`synctex_parser.c
mv -f .deps/libsynctex_a-synctex_parser.Tpo .deps/libsynctex_a-synctex_parser.Po
gcc -DHAVE_CONFIG_H -I.    -w  -g -O2 -MT libsynctex_a-synctex_parser_utils.o -MD -MP -MF .deps/libsynctex_a-synctex_parser_utils.Tpo -c -o libsynctex_a-synctex_parser_utils.o `test -f 'synctex_parser_utils.c' || echo './'`synctex_parser_utils.c
mv -f .deps/libsynctex_a-synctex_parser_utils.Tpo .deps/libsynctex_a-synctex_parser_utils.Po
rm -f libsynctex.a
ar cru libsynctex.a libsynctex_a-synctex_parser.o libsynctex_a-synctex_parser_utils.o 
ranlib libsynctex.a
gcc -DHAVE_CONFIG_H -I.    -Wall -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/poppler/0.62.0/include/poppler/glib -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -g -O2 -MT epdfinfo-epdfinfo.o -MD -MP -MF .deps/epdfinfo-epdfinfo.Tpo -c -o epdfinfo-epdfinfo.o `test -f 'epdfinfo.c' || echo './'`epdfinfo.c
epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is provided
      for compatibility reasons only. Due to security concerns inherent in the
      design of tempnam(3), it is highly recommended that you use mkstemp(3)
      instead. [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");
                  ^
/usr/include/stdio.h:395:1: note: 'tempnam' has been explicitly marked
      deprecated here
__deprecated_msg("This function is provided for compatibility reasons on...
^
/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
                                                      ^
1 warning generated.
mv -f .deps/epdfinfo-epdfinfo.Tpo .deps/epdfinfo-epdfinfo.Po
g++ -DHAVE_CONFIG_H -I.    -Wall -Wall -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/poppler/0.62.0/include/poppler/glib -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -std=c++11 -g -O2 -MT epdfinfo-poppler-hack.o -MD -MP -MF .deps/epdfinfo-poppler-hack.Tpo -c -o epdfinfo-poppler-hack.o `test -f 'poppler-hack.cc' || echo './'`poppler-hack.cc
mv -f .deps/epdfinfo-poppler-hack.Tpo .deps/epdfinfo-poppler-hack.Po
g++ -Wall -Wall -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/poppler/0.62.0/include/poppler/glib -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/poppler/0.62.0/include/poppler -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -std=c++11 -g -O2   -o epdfinfo epdfinfo-epdfinfo.o epdfinfo-poppler-hack.o -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation -L/usr/local/Cellar/poppler/0.62.0/lib -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -L/usr/local/lib -lpoppler-glib -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation -lcairo -L/usr/local/Cellar/poppler/0.62.0/lib -lpoppler -L/usr/local/Cell.-(~/devel/rep.-(~/devel/rep.-(~/devel/repos/pdf-tools)--------------------------(chrstfer@ChristophersMBP)-
`--> 
```

Noticeably, it also tramples the frame buffer--or whatever its called--a bit, as if it had output non-character data to stdio. This is all after a `make distclean && make clean`.
